//
// Created by Pablo Lobato on 12/12/2023.
//

#ifndef COLECCI_N_DE_EJERCICIOS_PROGRAMACI_N_ESTRUCTURADA_EJ1_H
#define COLECCI_N_DE_EJERCICIOS_PROGRAMACI_N_ESTRUCTURADA_EJ1_H


class EJ1 {

};


#endif //COLECCI_N_DE_EJERCICIOS_PROGRAMACI_N_ESTRUCTURADA_EJ1_H
